# https://pages.github.com/versions/
fork: false
repo_slug: harbour/core
site_slug: harbour/harbour.github.io
site_branch_and_root: master/
dl_url: https://sourceforge.net/projects/harbour-project/files/
short_version: "3.0"
license_file: COPYING.txt

exclude: ['*.pem', '*.sh']

example_categories:
  - basic
  - arrays
  - database
  - extensions
  - web
collections:
  example:
    output: true
defaults:
  - scope:
      path: ""
      type: example
    values:
      layout: example

incremental: true
sass:
  style: compressed
